language: haxe
haxe:
  - stable

hxml:
  - build-prod.hxml
  - test.hxml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: public
  on:
    branch: master