language: haxe
haxe:
  - stable

hxml:
  - build-prod.hxml
  - test.hxml

deploy:
  provider: pages
  # Temporary fix for broken Travis deploy, https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: pages-ivar-set
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: public
  on:
    branch: master